"""Descriptor table over center keys, indexed like the embedding table.

Generated by scripts/gen_joker_features.py from the game's own display
text plus jackdaw's centers. Rows for non-joker keys are zero: only
jokers have mechanics worth describing, and a zero row is exactly the
"no descriptor" signal.

The point is generalisation. A bare ID embedding shares nothing between
mechanically similar jokers, so each must be learned from its own
exposures -- and a given RARE appears roughly once every 18 games. With
a descriptor, an unseen rare inherits from commons that behave like it.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np

from balatro_zero.state import N_EMBED, center_key_id

DATA = Path(__file__).parent / "data" / "joker_features.json"


@lru_cache(maxsize=1)
def descriptor_table() -> np.ndarray:
    """[N_EMBED, D] float32, row i = descriptor for center id i."""
    if not DATA.exists():
        raise FileNotFoundError(
            f"{DATA} missing -- run scripts/gen_joker_features.py"
        )
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    dim = int(payload["dim"])
    table = np.zeros((N_EMBED, dim), dtype=np.float32)
    hits = 0
    for key, entry in payload["jokers"].items():
        idx = center_key_id(key)
        if idx:  # 0 is the pad/unknown slot; never write it
            table[idx] = np.asarray(entry["features"], dtype=np.float32)
            hits += 1
    if hits == 0:
        raise RuntimeError(
            "no joker key mapped to a center id -- the descriptor file and "
            "the embedding index have diverged"
        )
    return table


@lru_cache(maxsize=1)
def descriptor_dim() -> int:
    return int(descriptor_table().shape[1])


@lru_cache(maxsize=1)
def feature_names() -> tuple[str, ...]:
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    return tuple(payload["feature_names"])
